let mydate= new Date()
// console.log(mydate)
// console.log(mydate.toDateString())
// console.log(mydate.toJSON())
// let myTimeStemp=Date.now()
// console.log(myTimeStemp)
console.log(mydate.getDate())
console.log(mydate.getDay())
console.log(mydate.getTime())
console.log(mydate.getMonth()+1)